version: "3.9"

services:
    db:
        container_name: pg_container
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=playground
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    pgAdmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5555:80"
